# Generated by Django 4.0.5 on 2022-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
